import Providers from "@/components/providers";
import "@/styles/globals.css";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = Montserrat({
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${font.className}`}>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
